#!/bin/bash

asm(){
	if [ $# != 1 ];then
		echo "usage : asm file.s"
		return
	fi

	local arg=$(echo $1 | cut -d . -f 1)
	assemble $arg elf32 && asmlink $arg elf_i386 && asmclean $arg;
}

assemble(){
	nasm -f $2 $1.s -o $1.o && return 0 || return 1
}

asmlink(){
	ld -m $2 $1.o -o $1 && return 0 || return 1
}

asmclean(){
	rm $1.o
}
